# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 912394b35e5f31560aa3b3c884b406f11850622d212f8b198cad76770d1879daf6b1f0d356b3177637e64ffc7e4eae4f98ccea6f6c4342f2baf40b23560659fe

test:
  secret_key_base: 3764867e6006fb34a9457bb534832ea6913aa09f55ca7145389eb9fc16264ec57abf83adef84c6470fb138f9a179a1b45666a98c81f6ae18c133793e1107c10f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
